FROM vllm/vllm-openai:v0.11.2

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# Project Env
WORKDIR /workspace

ENTRYPOINT []